apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgB57W5+uWN6M0E8qN8S/0NlwvKWXu4OarfEqTYhWbfqfIQuX6GfOis8NYdXzwdC1kPEO+EWHvYHtTs5NgPh6lC0pldzPJe8k6WFt8n46UtbWZ6MAijS9M1lv03q8NEpPe65TKpmhv2fM8GgFXLttrRTI33pSVU9SnS/ex/kgN7VX/D+w16Y2h5hvYRIQ5LI9bqB8f8vVgIGqcqjqFeZJcD77tTq/cKqOxK4RZTAWdORkBU2focyXV6qEml8irZ0m/hQ0Z+Hbv1VbTsEPf3DHKFyqtTZZ+iMajcKwU0m5rtcsO9bufhgdGT5me6JToItrlE4ZaKMqZ9Twd34ZWKeAFvDqUmgtDMo2pPqNfs/LiAEfrxIOnLcoMYXd4Y7KA+A5/1EvtQytcDc9OgTkKoVEa217TKBTU7W1g+hCznip6swmg0q9Dh1wuUEhwRV+OVzKUXSikB+L920LqkGBFXa59ewGjhjdriu8B4TNScyThr4W+DMZoSIWL7zssMDUr32sMJB4FZI4M/Ejivfc0OEezMTcWlTZ7sp2gitIWnVG13A5cHZfgALh3oxt0SkPJRV/xDwvV6s+7MgVUfz5eD2hJQtkUPu80MhZSu+LqxRxtJvdoM6arbw4gwbGqzNLIylwpUciwVbcoZS1cl8fc6IR/39WsgJD5DQ2stkhwbxYkpDEvSm+HhpNZwW/Ko7OqUEhtZY2InlcrZ0wTI=
    username: AgDHByiJArFJpzgZ/SvJ+iZGOg5C7ZiPdA+xBsBsJa82DuJDJUGbit1mkScjkIrZBQKGQBns3g8A9sLDIZijgx/T/3wwiN+2pxiQx+93srwWJ9yLsZh2G5yzzEMKs0puaVIq6xy6acaHKwGT+tVx24BLWNiXJSnDzJ1kDV+bqwFpLrObLGDp1MRfn0iKqsB4eBg+VxMVPUeHJpnABjTlVz3CGAXZkDeAxI+yyXRXCsz3NP9cvXfauXC21bKtYy0FvLNceKFq8L12a54JXnaFMd+2vDxY/PT06iqWsE3MjXhFGnk9C/f5flE8zGxl4WxrPgXFRspRHhn+9BTKA0Zx2OiYuFog92kF6xfc/Q55AomdfJOK/BaY5Ru1Ss9eArQEdWJuRTIaLs0NI60pJNlSCyZzuf8uL5e358vOSpHKynB9iWE7UakYcynZ2A2H/jH6A50RJm5j6XCbp5xpoW8qGubVXc7fvMPxv+VQc9DJE8yi9DAp2gmgdcLI8glwiMP3YG1XsQ3GCWRVhhIWp5984nZv8edCBDhOoatSXueTxPVsvUQwrcxzAOUcyuRLM4BeEe63FTXKcsvqOGXYWsIPDIVMOQSW3vOE2yuNgNXSr2UuZzdrEEJnRFXMZuL0x6/oJy67fdTrXJE7MCYRlbNcABhWHfk61zrcXdXxSgZnaxVyJcXINEffis7V7CuO8RSrUnNtF0eKig==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

